version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"  # Path to the "package.json" file from the main repo directory
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    
    # Groups multiple small updates into a single pull request
    groups:
      safe-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    
    # Prevents Dependabot from creating PRs for major version updates
    ignore:
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]